baseURL = 'https://blog.md888.cc/'
languageCode = 'zh-CN'
title = '毛豆 Facebook'
theme = 'stack'
timeZone = 'Asia/Shanghai'
enableRobotsTXT = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
