module:
    hugoVersion:
        extended: true
        min: "0.87.0"
              
### Custom menu
### See https://stack.jimmycai.com/config/menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - name: 关于我们
          url: /posts/sale-fb-account/
          weight: 100
          params:
            #icon: flame
    social:
        - identifier: telegram
          name: Telegram
          url: https://t.me/maodou0001
          params:
              icon: brand-telegram

        - identifier: shop
          name: Shop
          url: https://www.maodou168.top/
          params:
              icon: world-www
params:         
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since:
        customText:

    dateFormat:
        published: 2025-08-01
        lastUpdated: 2025-08-01 00:00:00

    sidebar:
        compact: false
        emoji: 
        subtitle: Facebook 海外账号批发
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        headingAnchor: false
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:        

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client/props.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - nick
                - mail
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            strict:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition:
            lang:

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:

    widgets:
        homepage: []
        page: []

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
